---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::pip==26.0.1
  - conda-forge::python=3.14.3
  - pip:
      - paraphrase==0.2.0
